name: Fetch and Process e-Gov Data

on:
  schedule:
    - cron: "0 0 * * *"  # 毎日0:00 UTCに実行（日本時間9:00）
  workflow_dispatch:     # 手動でも実行可能

jobs:
  fetch-process:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run data fetch and process scripts
      run: |
        python scripts/fetch_data.py
        python scripts/process_data.py

    - name: Commit & Push processed data
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add data/processed.csv
        git commit -m "Auto update data"
        git push
